---
- name: Restart system
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after NVIDIA driver installation"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  listen: "restart after nvidia install"
