---
- name: Destroy VM instances
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    qemu_pid_file: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}/{{ molecule_yml.platforms[0].instance_name }}.pid"

  tasks:
    - name: Print Platform Information
      debug:
        msg:
          - "Platform Name: {{ molecule_yml.platforms[0].name }}"
          - "Instance Name: {{ molecule_yml.platforms[0].instance_name }}"
          - "Memory: {{ molecule_yml.platforms[0].memory }}"
          - "CPUs: {{ molecule_yml.platforms[0].cpus }}"
          - "Ansible User: {{ molecule_yml.platforms[0].ansible_user }}"
          - "Private Key: {{ molecule_yml.platforms[0].ansible_private_key_file }}"
          - "QEMU PID File: {{ qemu_pid_file }}"

    - name: Set platform specific variables
      set_fact:
        instance_name: "{{ molecule_yml.platforms[0].instance_name }}"
        image_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/{{ molecule_yml.platforms[0].instance_name }}.qcow2"
        cloud_init_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/{{ molecule_yml.platforms[0].instance_name }}-cloud-init.iso"

    - name: Load instance config
      set_fact:
        instance_config: "{{ lookup('file', molecule_instance_config) | from_yaml }}"
      when: molecule_instance_config is defined and molecule_instance_config != ''
      ignore_errors: true

    - name: Get PID file path
      set_fact:
        qemu_pid_file: "{{ qemu_pid_file }}"
      when: instance_config is defined
      ignore_errors: true

    - name: Check if PID file exists
      stat:
        path: "{{ qemu_pid_file }}"
      register: pid_file_stat
      when: qemu_pid_file is defined and qemu_pid_file != ''
      ignore_errors: true

    - name: Read PID from file
      command: "cat {{ qemu_pid_file }}"
      register: vm_pid
      when: pid_file_stat is defined and pid_file_stat.stat.exists
      changed_when: false
      ignore_errors: true

    - name: Kill QEMU process
      shell: "kill {{ vm_pid.stdout }}"
      when: vm_pid is defined and vm_pid.stdout | length > 0
      ignore_errors: true
      changed_when: true

    - name: Remove instance disk image and other artifacts
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ image_path }}"
        - "{{ cloud_init_path }}"
        - "{{ qemu_pid_file }}"
        - "{{ qemu_pid_file }}.monitor"
      ignore_errors: true

    - name: Cleanup instance config
      file:
        path: "{{ molecule_instance_config }}"
        state: absent
      when: molecule_instance_config is defined and molecule_instance_config != ''
      ignore_errors: true
