---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
platforms:
  - name: test-vm
    instance_name: nvidia-test-${MOLECULE_SCENARIO_NAME:-default}
    groups:
      - molecule
    memory: 4096
    cpus: 4
    connection: ssh
    ansible_connection: ssh
    ansible_user: molecule
    ansible_private_key_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
    managed: false
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible-${USER}/tmp
  inventory:
    host_vars:
      test-vm:
        ansible_user: molecule
        ansible_private_key_file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
        ansible_become: true
verifier:
  name: testinfra
  directory: ../tests
  options:
    v: true
    s: true
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
