---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Print Platform Information
      debug:
        msg:
          - "Platform Name: {{ molecule_yml.platforms[0].name }}"
          - "Instance Name: {{ molecule_yml.platforms[0].instance_name }}"
          - "Memory: {{ molecule_yml.platforms[0].memory }}"
          - "CPUs: {{ molecule_yml.platforms[0].cpus }}"
          - "Ansible User: {{ molecule_yml.platforms[0].ansible_user }}"
          - "Private Key: {{ molecule_yml.platforms[0].ansible_private_key_file }}"

    - name: Install prerequisites for RedHat systems
      package:
        name:
          - curl
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install prerequisites for Debian systems
      apt:
        name:
          - apt-utils
          - gpg
          - wget
          - curl
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Create directories for mock RPMs
      file:
        path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/files"
        state: directory
        mode: '0755'

    - name: Create directory structure for mock NVIDIA driver
      file:
        path: "/usr/lib/modules/{{ ansible_kernel }}/extra/nvidia"
        state: directory
        mode: '0755'

    - name: Create mock NVIDIA driver RPM for testing
      copy:
        dest: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/files/mock-nvidia-driver.rpm"
        content: "mock package"
        mode: '0644'

    - name: Create mock CUDA Toolkit RPM for testing
      copy:
        dest: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/files/mock-cuda-toolkit.rpm"
        content: "mock package"
        mode: '0644'

    - name: Create mock NVIDIA kernel module
      copy:
        dest: "/usr/lib/modules/{{ ansible_kernel }}/extra/nvidia/nvidia.ko"
        content: "// Mock NVIDIA kernel module for testing"
        mode: '0644'

    - name: Create mock NVIDIA utilities
      file:
        path: "/usr/bin/{{ item }}"
        state: touch
        mode: '0755'
      with_items:
        - nvidia-smi
        - nvidia-settings
        - nvidia-persistenced
        - nvidia-fabricmanager
      changed_when: false

    - name: Create mock CUDA directories
      file:
        path: "/usr/local/{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - cuda-12.8
        - cuda-12.8/bin

    - name: Create mock CUDA binaries
      file:
        path: "/usr/local/cuda-12.8/bin/{{ item }}"
        state: touch
        mode: '0755'
      with_items:
        - nvcc
        - cuda-gdb
        - cuda-memcheck
      changed_when: false

    - name: Create symbolic link for CUDA
      file:
        src: "/usr/local/cuda-12.8"
        dest: "/usr/local/cuda"
        state: link

    - name: Update system prior to testing
      package:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat" and false

    - name: Update system prior to testing (Ubuntu)
      apt:
        upgrade: full
        update_cache: true
      when: ansible_os_family == "Debian"
